on: [push, pull_request, workflow_dispatch]

name: Build

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: zmkfirmware/zmk-build-arm:stable
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get version data
        id: get_info
        run: |
          timestamp=$(date +"%Y%m%d%H%M")
          commit=$(echo "${{ github.sha }}" | cut -c1-7)
          file_prefix=$timestamp-$commit
          branch_name=$(echo "${{ github.ref }}" | awk -F'/' '{print $3}' | cut -c1-4)
          echo "file_prefix=$file_prefix" >> $GITHUB_OUTPUT
          ./get_version.sh $branch_name $commit
      - name: Cache west modules
        uses: actions/cache@v4
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('manifest-dir/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: West Init
        run: west init -l config
      - name: West Update
        run: west update
      - name: West Zephyr export
        run: west zephyr-export
      - name: West Build (Form)
        run: west build -s zmk/app -b stp -S studio-rpc-usb-uart -- -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"
      - name: Form Kconfig file
        run: grep -vE '(^#|^$)' build/zephyr/.config
      - name: Rename zmk.uf2
        run: cp build/zephyr/zmk.uf2 ${{ steps.get_info.outputs.file_prefix }}-Form.uf2 
      - name: Archive (Form)
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: |
            ${{ steps.get_info.outputs.file_prefix }}-Form.uf2
